[package]
name = "btsrch"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
eframe = "0.32.0"
egui = "0.32.0"
open = "5.3.2"
regex = "1.11.1"
single-instance = "0.3.3"
tokio = { version = "1.46.1", features = ["full"] }
