pub mod app_parser;
pub mod custom_commands_parser;
pub mod link_parser;
pub mod path_parser;
pub mod unit_calc_parser;
pub mod unicode_parser;
pub mod command_parser;
pub mod cliphist_parser;
pub mod regex_to_command;